providers:
  parent: http://localhost:8547
  main: http://localhost:3347
  # main: http://localhost:3347
single-options:
  per-tx: 30
  private-key: 
  transaction-options:
    value: 100000000000000
    gas: 30000
    gas-price:
    data:
    to: 
multi-options:
  per-tx: 10
  private-key-range:
    start-index: 0
    total: 10 # MAX 100000
  transaction-options:
    value: 100000000000000
    gas: 30000
    gas-price:
    data:
    to: 
distribute-options:
  private-key: 
  value: 1000000000000000000
  gas: 
  gas-price: 300000000